name: release project
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./public