name: release project
on: 
  push:
    branches:
      - main
  workflow_dispatch:

runs:
  using: "composite"
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: GitHub Action for Yarn
      uses: actions/setup-dotnet@v1
      uses: Borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v3.0.0
      with:
        cmd: build
    - name: Vercel Action
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
        working-directory: ./public